# Principled Preferential Bayesian Optimization
# https://arxiv.org/abs/2402.05367
#
# Main algorithm

# @package _global_

defaults:
  - /default
  - _self_

seed: 42

social_welfare_function: beale

reward_type: tw
learning_algorithm: oracle

kernel_type: matern

RKHS_bound: 20
beta: 2

horizon: 30

learn_utilities: False