name: pref
channels:
  - defaults
dependencies:
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - expat=2.5.0
  - flake8=7.0.0
  - libcxx=14.0.6
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - llvm-openmp=14.0.6
  - mccabe=0.7.0
  - ncurses=6.4
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.0.13
  - pip=23.3.1
  - pycodestyle=2.11.1
  - pyflakes=3.2.0
  - python=3.12.0
  - pywavelets=1.5.0
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - asttokens==2.4.1
      - blinker==1.7.0
      - casadi==3.6.5
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - comm==0.2.2
      - contourpy==1.2.0
      - cycler==0.12.1
      - cython==3.0.9
      - dash==2.16.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - decorator==5.1.1
      - docker-pycreds==0.4.0
      - executing==2.0.1
      - flask==3.0.2
      - fonttools==4.50.0
      - gitdb==4.0.11
      - gitpython==3.1.42
      - gpy==1.13.1
      - hydra-core==1.3.2
      - idna==3.6
      - importlib-metadata==7.1.0
      - iniconfig==2.0.0
      - ipython==8.22.2
      - ipywidgets==8.1.2
      - itsdangerous==2.1.2
      - jedi==0.19.1
      - jinja2==3.1.3
      - jupyterlab-widgets==3.0.10
      - kiwisolver==1.4.5
      - markupsafe==2.1.5
      - matplotlib==3.8.3
      - matplotlib-inline==0.1.6
      - nest-asyncio==1.6.0
      - omegaconf==2.3.0
      - packaging==24.0
      - pandas==2.2.1
      - paramz==0.9.6
      - parso==0.8.3
      - pexpect==4.9.0
      - pillow==10.2.0
      - plotly==5.20.0
      - pluggy==1.4.0
      - pref==0.0.1
      - prompt-toolkit==3.0.43
      - protobuf==4.25.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pygments==2.17.2
      - pyparsing==3.1.2
      - pytest==8.1.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.1
      - requests==2.31.0
      - retrying==1.3.4
      - scipy==1.11.4
      - sentry-sdk==1.44.0
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - stack-data==0.6.3
      - tenacity==8.2.3
      - tqdm==4.66.2
      - traitlets==5.14.2
      - typing-extensions==4.10.0
      - tzdata==2024.1
      - urllib3==2.2.1
      - wandb==0.16.5
      - wcwidth==0.2.13
      - werkzeug==3.0.1
      - widgetsnbextension==4.0.10
      - zipp==3.18.1
